version: "3.7"
services:
  calcifer:
    build:
      context: ./calcifer
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
     - ./calcifer:/app
  ghi:
    image: node:latest
    command: npm start
    working_dir: /app
    volumes:
      - ./ghi/react-app:/app
    environment:
      - HOST=0.0.0.0
      - PORT=3001
    ports:
      - "3001:3001"
