version: "3.7"
volumes:
    postgres-data:
        external: true
services:
  db:
    image: postgres:14.5-bullseye
    volumes:
        - postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
  calcifer:
    build:
      context: ./calcifer
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
     - ./calcifer:/app
    depends_on:
      - db
  ghi:
    image: node:latest
    command: npm start
    working_dir: /app
    volumes:
      - ./ghi/react-app:/app
    environment:
      - HOST=0.0.0.0
      - PORT=3001
    ports:
      - "3001:3001"
